@startuml Prototype
class Manager{
    - showcase
    + register()
    + create()
}
interface Animal{
    + cry()
    + createClone()
}
class Neko implements Animal{
    - name
    + cry()
    + createClone()
}
class Inu implements Animal{
    - name
    + cry()
    + createClone()
}
class SoAndSo implements Animal{
    - name
    - gobi
    + cry()
    + createClone()
}
Manager-->Animal :Uses
@enduml
